<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-FEJVQKG" name="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase" tests="3" failures="1" timestamp="2021-10-23T10:48:26 IST" time="210.480" errors="0">
  <testcase name="TC02_LoginCheck_InvalidCredentials" time="87.510" classname="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase">
    <failure type="java.lang.AssertionError" message="expected [The combination of user name and password you entered does not match any existing accounts. Please try again...] but found [The combination of user name and password you entered does not match any existing accounts. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [The combination of user name and password you entered does not match any existing accounts. Please try again...] but found [The combination of user name and password you entered does not match any existing accounts. Please try again.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.perfaware.automation.oms.sterling.common.com.pageobjects.Page_Login.captureLoginError(Page_Login.java:69)
at com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase.TC02_LoginCheck_InvalidCredentials(DemoTestcase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- TC02_LoginCheck_InvalidCredentials -->
  <system-out/>
  <testcase name="TC01_LoginCheck_ValidCredentials" time="110.138" classname="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase"/>
  <system-out/>
  <testcase name="TC02_LoginCheck_InvalidCredentials" time="12.832" classname="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase">
    <skipped/>
  </testcase> <!-- TC02_LoginCheck_InvalidCredentials -->
  <system-out/>
</testsuite> <!-- com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase -->
